package com.ollama.Ollama.Services;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import org.springframework.ai.chat.model.ChatModel;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.ollama.Ollama.model.ChatResponse;

/**
 * Service class responsible for handling chat interactions. Manages chat
 * sessions, processes user prompts, updates chat context, and stores chat
 * history in files for future reference.
 */
@Service
public class ChatService {

	/** Base project path for storing chat context files. */
	@Value("${projectPath}")
	private String projectPath;

	/** Chat model instance for generating responses. */
	private final ChatModel chatModel;

	/** Lock object to ensure thread-safe file operations. */
	private final Object fileLock = new Object(); // Lock for thread safety

	/** A thread-safe map to maintain chat contexts by chat ID. */
	private final Map<String, StringBuilder> chatContextMap = new ConcurrentHashMap<>(); // Store chat context

	/**
	 * Constructor to initialize the chat service with the specified chat model.
	 *
	 * @param chatModel the chat model used for processing prompts and generating
	 *                  responses.
	 */
	private ChatService(ChatModel chatModel) {
		this.chatModel = chatModel;
	}

	/**
	 * Handles the chat flow by processing user prompts and returning responses.
	 *
	 * @param chatId the unique identifier for the chat session.
	 * @param prompt the user's input message.
	 * @return a {@link ChatResponse} object containing the conversation ID and
	 *         response content.
	 */
	public ChatResponse handleChat(String chatId, String prompt) {
		if (chatId == null || chatId.isEmpty()) {
			// Start a new chat
			chatId = startChat();
		}

		// Process prompt in the context of the chatId
		String response = processPrompt(chatId, prompt);
		ChatResponse chat = new ChatResponse();
		chat.setConversationId(chatId);
		chat.setResponseContent(response);

		return chat;
	}

	/**
	 * Starts a new chat session by generating a unique chat ID and initializing its
	 * context.
	 *
	 * @return the newly generated unique chat ID.
	 */
	private String startChat() {
		String chatId = UUID.randomUUID().toString(); // Generate unique chat ID
		chatContextMap.put(chatId, new StringBuilder()); // Initialize context
		return chatId;
	}

	/**
	 * Processes a user prompt and retrieves the chat model's response. Updates the
	 * chat context and saves the chat history to a file.
	 *
	 * @param chatId the unique identifier of the chat session.
	 * @param prompt the user's input message.
	 * @return the response generated by the chat model.
	 * @throws IllegalArgumentException if the chat ID is invalid.
	 */
	private String processPrompt(String chatId, String prompt) {
		if (!chatContextMap.containsKey(chatId)) {
			throw new IllegalArgumentException("Invalid chatId: Chat session not found!");
		}

		// Get the response from the chat model
		String response = chatModel.call(prompt);

		// Update chat context
		updateChatContext(chatId, prompt, response);

		// Save the context to file
		saveContextToFile(chatId);

		return response;
	}

	/**
	 * Updates the chat context with the given prompt and response.
	 *
	 * @param chatId   the unique identifier of the chat session.
	 * @param prompt   the user's input message.
	 * @param response the response generated by the chat model.
	 */
	// Update chat context with prompt and response
	private void updateChatContext(String chatId, String prompt, String response) {
		StringBuilder context = chatContextMap.get(chatId);
		synchronized (context) {
			context.append("Prompt: ").append(prompt).append("\n");
			context.append("Response: ").append(response).append("\n");
			context.append("=========================================\n");
		}
	}

	// Save the chat context to a file

	/**
	 * Updates the chat context with the given prompt and response.
	 *
	 * @param chatId   the unique identifier of the chat session.
	 * @param prompt   the user's input message.
	 * @param response the response generated by the chat model.
	 */
	private void saveContextToFile(String chatId) {
		String filePath = projectPath + File.separator + "responses/chat_" + chatId + ".txt";

		synchronized (fileLock) {
			File file = new File(filePath);
			file.getParentFile().mkdirs();

			try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
				writer.write("Chat ID: " + chatId + "\n");
				writer.write(chatContextMap.get(chatId).toString());
			} catch (IOException e) {
				e.printStackTrace();
				System.err.println("Failed to write chat context to file.");
			}
		}
	}
}
